version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./docker/.gitconfig:/root/.gitconfig
    working_dir: /app
    tty: true
    environment:
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_DEFAULT_CHANNEL=${SLACK_DEFAULT_CHANNEL}
